import { useAuth } from '@/hooks/useAuth'
import { fmtAmount, type PayrollRun } from './payrollShared'

interface Props {
  run: PayrollRun
  onClose: () => void
}

interface Row { label: string; desc: string; amount: number }

export function PayslipView({ run, onClose }: Props) {
  const { user } = useAuth()

  const earnings: Row[] = [
    { label: 'Gross Salary', desc: run.gross_salary_desc, amount: run.gross_salary },
    { label: 'Overtime', desc: run.overtime_desc, amount: run.overtime_amount },
    { label: 'Incentive', desc: run.incentive_desc, amount: run.incentive_amount },
    { label: 'Commission', desc: run.commission_desc, amount: run.commission_amount },
  ].filter(r => r.amount > 0 || r.label === 'Gross Salary')

  const deductions: Row[] = [
    { label: 'CPF', desc: run.cpf_desc, amount: run.cpf_amount },
    { label: 'Insurance', desc: run.insurance_desc, amount: run.insurance_amount },
    { label: run.other_deduction_desc || 'Other', desc: '', amount: run.other_deduction_amount },
  ].filter(r => r.amount > 0)

  const grossTotal = earnings.reduce((s, r) => s + r.amount, 0)
  const deductionsTotal = deductions.reduce((s, r) => s + r.amount, 0)

  return (
    <div className="fixed inset-0 z-50 flex items-start sm:items-center justify-center bg-black/40 p-4 overflow-y-auto">
      <div className="no-print flex justify-end w-full max-w-2xl mb-2">
        <button onClick={onClose} className="text-white/80 hover:text-white text-sm font-medium">
          Close ✕
        </button>
      </div>

      <div className="print-area bg-white rounded-2xl shadow-xl w-full max-w-2xl p-8 sm:p-10">
        <div className="flex items-start justify-between border-b border-gray-100 pb-6 mb-6">
          <div>
            <p className="font-heading text-lg font-extrabold text-gray-900">{run.user?.name ?? user?.sub_account}</p>
            <p className="text-sm text-gray-500">{run.user?.email}</p>
          </div>
          <div className="text-right">
            <p className="text-xs font-semibold text-violet-600 uppercase tracking-wide">Payslip</p>
            <p className="text-sm text-gray-500 mt-0.5">
              {new Date(run.payment_date).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}
            </p>
            <p className="text-xs text-gray-400 mt-0.5">{user?.sub_account}</p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-8">
          <div>
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">Earnings</p>
            <div className="space-y-2.5">
              {earnings.map(r => (
                <div key={r.label} className="flex items-start justify-between gap-3 text-sm">
                  <div>
                    <p className="text-gray-800">{r.label}</p>
                    {r.desc && <p className="text-xs text-gray-400">{r.desc}</p>}
                  </div>
                  <p className="font-mono text-gray-900 whitespace-nowrap">{fmtAmount(r.amount, run.currency)}</p>
                </div>
              ))}
            </div>
            <div className="flex items-center justify-between text-sm font-semibold text-gray-900 border-t border-gray-100 mt-3 pt-3">
              <span>Gross Total</span>
              <span className="font-mono">{fmtAmount(grossTotal, run.currency)}</span>
            </div>
          </div>

          <div>
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">Deductions</p>
            {deductions.length === 0 ? (
              <p className="text-sm text-gray-400">No deductions</p>
            ) : (
              <div className="space-y-2.5">
                {deductions.map(r => (
                  <div key={r.label} className="flex items-start justify-between gap-3 text-sm">
                    <p className="text-gray-800">{r.label}</p>
                    <p className="font-mono text-gray-900 whitespace-nowrap">−{fmtAmount(r.amount, run.currency)}</p>
                  </div>
                ))}
              </div>
            )}
            <div className="flex items-center justify-between text-sm font-semibold text-gray-900 border-t border-gray-100 mt-3 pt-3">
              <span>Deductions Total</span>
              <span className="font-mono">−{fmtAmount(deductionsTotal, run.currency)}</span>
            </div>
          </div>
        </div>

        <div className="mt-8 bg-violet-50 border border-violet-200 rounded-xl px-5 py-4 flex items-center justify-between">
          <span className="text-sm font-semibold text-violet-800">Net Pay</span>
          <span className="text-xl font-mono font-bold text-violet-900">{fmtAmount(run.net_pay, run.currency)}</span>
        </div>

        <p className="text-[11px] text-gray-300 text-center mt-8">
          Generated by DIGITRACKER on {new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}
        </p>
      </div>

      <div className="no-print flex justify-center w-full max-w-2xl mt-4">
        <button onClick={() => window.print()}
          className="bg-white hover:bg-gray-50 text-gray-900 rounded-lg px-5 py-2.5 text-sm font-semibold shadow-lg transition-colors">
          🖨️ Print / Save as PDF
        </button>
      </div>
    </div>
  )
}
